class ChangeDefaultPictures2 < ActiveRecord::Migration[5.2]
  def change
    change_column_default(:annonces, :photo, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:annonces, :photo1, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:annonces, :photo2, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:annonces, :photo3, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:annonces, :photo4, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:agents, :justif_entrepreneur, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:documents, :piece_jointe, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :id_recto, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :id_verso, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :justif_dom, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :fiche_paye_mois1, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :fiche_paye_mois2, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :fiche_paye_mois3, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataire_supplementaires, :contrat, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :id_recto, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :id_verso, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :justif_dom, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois1, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois2, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois3, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :contrat, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :id_recto_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :id_verso_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :justif_dom_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois1_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois2_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :fiche_paye_mois3_garant, "image/upload/v1582613499/default_annonce.png")
    change_column_default(:locataires, :contrat, "image/upload/v1582613499/default_annonce.png")
  end
end
